final_project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from picture_sharing import views
from django.conf.urls import static
from final_project import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^login/$', auth_views.login),
    url(r'^logout/$', auth_views.logout, {'next_page': '/'}),
    url('^', include('django.contrib.auth.urls')),
    url(r'^$', views.index),
    url(r'^popular', views.popular),
    url(r'^add', views.add),
    url(r'^private$', views.private),
    url(r'^delete/(\w+)', views.delete),
    url(r'^like', views.like),
    url(r'^admin', admin.site.urls),
    url(r'^(?P<key>\w+)$', views.show_image, name='image'),
]

if settings.DEBUG:
        from django.conf.urls.static import static
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

picture_sharing/models.py
from django.db import models
from datetime import datetime
from django.utils.baseconv import base56
from random import randint
from django.contrib.auth.models import User

# Create your models here.

def random_key():
    return base56.encode(randint(0, 0x7fffff))

class Picture(models.Model):
    image = models.ImageField(default = 'pic_folder/None/no-img.jpg')
    description = models.CharField(max_length=100, default='')
    key = models.SlugField(max_length=10, unique=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_last_view = models.DateTimeField(null=True, auto_now=True)
    views_count = models.PositiveIntegerField(default=0)
    #likes_count = models.PositiveIntegerField(default=0)
    user = models.CharField(max_length=20, default='anonymous')
    #auth_user = models.OneToOneField(User)

    def __str__(self):
        return self.key + ' : ' +str(self.image)
        
    @classmethod
    def create(cls, image, user, description=''):
        created = False
        while created == False:
            key = random_key()
            obj, created = cls.objects.get_or_create(key=key, defaults={'image': image, 'description': description, 'user': user})
        #l = Like.objects.create(id=obj.id)
        return obj

#    def delete(self, key):
#        instance = Picture.objects.get(key=key)
#        instance.delete()
#        return 0

#   def view(self, key):
#       instance = Picture.objects.get(key=key)
#       return instance

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('image', kwargs={'key': self.key})
        
        
class Like(models.Model):
    id = models.OneToOneField(Picture, primary_key=True)
    likes = models.PositiveIntegerField(default=0)
    
    def __str__(self):
        #p = Picture.objects.get(id=self)
        return str(self.id)# + ' : ' + str(p.key)

picture_sharing/views.py
from django.shortcuts import render, redirect
from django import forms
from picture_sharing.models import Picture, Like
from django.http import HttpResponse
from django.db.models import F
from django.contrib import messages
try:
    from django.utils import simplejson as json
except ImportError:
    import json


from django.conf import settings
import os
import final_project.settings

# -*- coding: utf8 -*-
# Create your views here.

class ImageUploadForm(forms.Form):
    """Image upload form."""
    image = forms.ImageField()
    description = forms.CharField(max_length=100, label='Description', initial='Test description')



"""  Main page  """
def index(request):
    
    p = Picture.objects.order_by('-date_created')[:12]
    ctx = {'pictures' : p }
    ctx['page_title'] = 'Recent images(by date)'
    ctx['active_tab'] = 'main'
    return render(request, 'index.html', ctx)

""" Popular """
def popular(request):
    
    p = Picture.objects.order_by('-views_count')[:12]
    ctx = {'pictures' : p }
    ctx['page_title'] = 'Popular images(by views)'
    ctx['active_tab'] = 'popular'
    return render(request, 'index.html', ctx)
    
""" Add image """
def add(request):
    
    ctx = {}
    if request.method == 'POST':
        form = ImageUploadForm(request.POST, request.FILES)
        if request.user.is_authenticated():
            user = str(request.user)
        else:
            user = 'anonymous'
        if form.is_valid():
            obj = Picture.create(image=form.cleaned_data['image'], description=form.cleaned_data['description'], user=user)
            messages.success(request, 'image upload success')
            l = Like(id=obj)
            l.save()
            
            
            
            return redirect('/' + str(obj.key))
    else:
        ctx['page_title'] = 'Add images'
        ctx['active_tab'] = 'add'
        return render(request, 'add.html', ctx)

""" Display one image and all its info """
def show_image(request, key):
    try:
        p = Picture.objects.get(key=key)
        ctx = {}
        ctx['date_last_view'] = p.date_last_view
        try:
            l = Like.objects.get(id=p.id)
            ctx['likes'] = l.likes
        except Exception as e:
            messages.error(request, 'Error...  '+str(e)+'   The key is: "'+str(key)+'"')
        p.views_count = F('views_count') + 1 #increase views counter
        p.save()

        p = Picture.objects.get(key=key)
        ctx['picture'] = p
        ctx['page_title'] = 'Image properties'
        ctx['image_info'] = str(key)
        return render(request, 'image.html', ctx)
    except Exception as e:
        
        messages.error(request, 'Error...  '+str(e)+'   The key is: "'+str(key)+'"')
        return redirect('/')

"""Delete image"""
def delete(request, key):
    try:
        obj = Picture.objects.get(key=key)
        print(str(settings.MEDIA_ROOT) + str(obj.image))
        if str(request.user) == str(obj.user):
            os.remove(str(settings.MEDIA_ROOT) + '\\' + str(obj.image))
            obj.delete()
        else:
            messages.error(request, 'You can not delete picture of user '+ str(obj.user) + ' because you are ' + str(request.user))
        return redirect('/')
    except Exception as e:
        messages.error(request, 'Error...  '+str(e)+'   The key is: "'+str(key)+'"')
        return redirect('/')

""" Add like to image """
def like(request):
    if request.method == "POST":
        rkey = request.POST.get('key', None)
        print('rkey = ' + rkey)
    
    try:
        p = Picture.objects.get(key=rkey)
        l = Like.objects.get(id=p.id)
        l.likes = F('likes') + 1
        l.save()
        print('Success')
        l = Like.objects.get(id=p.id)
        ctx = {}
        ctx['message'] = "You liked it"
        ctx['likes_count'] = l.likes
        return HttpResponse(json.dumps(ctx), content_type='application/json')
        #return redirect('/' + str(key))
    except Exception as e:
        print('Exception')
        messages.error(request, 'Error...  '+str(e)+'   The key is: "'+str(rkey)+'"')
        return redirect('/')
        
"""  User images  """
def private(request):
    
    #print(settings.BASE_DIR)
    #print(settings.MEDIA_ROOT)
    if request.user.is_authenticated():
        p = Picture.objects.order_by('-date_created').filter(user=str(request.user))[:12]
        ctx = {'pictures' : p }
        ctx['page_title'] = 'Recent images(by date) of user: '+str(request.user)
        ctx['active_tab'] = 'private'
        ctx['private'] = True
        return render(request, 'index.html', ctx)
    else:
        p = Picture.objects.order_by('-date_created').filter(user='anonymous')[:12]
        ctx = {'pictures' : p }
        ctx['page_title'] = 'Recent images(by date)'
        ctx['active_tab'] = 'private'
        ctx['private'] = True
        return render(request, 'index.html', ctx)

picture_sharing/templates/add.html
{% include "header.html" %}

<div class="container">
    <div class="panel panel-info">
    <div class="panel-heading">{{ page_title }}</div>
        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div style="padding-top:15px">
            <div class="form-group">
                <label for="id_image" class="col-sm-2 control-label">Select image to upload</label>
                <div class="col-sm-10">
                    <input id="id_image" type="file" class="" name="image">
                </div>
            </div>
            <div class="form-group">
                <label for="id_description" class="col-sm-2 control-label">Enter description</label>
                <div class="col-xs-6">
                    <input id="id_description" type="text" class="form-control" name="description" value='Test description' size='20'>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-info">Upload</button>
                </div>
            </div>
        </div>
        <!--<input style="padding-left:5px;" type="submit" value="Submit" />-->
        </form>
    </div>
</div>

{% include "footer.html" %}

picture_sharing/templates/footer.html
<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <p align=right>Created by Artem Prokopets. 2016</p>
         </div>
    </div>
</div>


  </body>
</html>

picture_sharing/templates/header.html
<!DOCTYPE html>
<html>
  <head>
    <title>Picture sharing</title>
    {% load staticfiles %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <!--<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">-->
  </head>
  <body>
    <!--<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>-->
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    <div class="container"><header style="text-align: center">
        <h1>Welcome to my picture sharing app</h1>
    </header></div>
    <div class="container">
    <div align=right>
      {{ user }}
      {% if user.is_anonymous %}
      <a href="/login/">login</a>
      {% else %}
      <a href="/logout/">logout</a>
      {% endif %}
    </div>
    </div>
    <div class="container">
        <ul class="nav nav-tabs">
            <li role="presentation" class="{% if active_tab == 'main' %}active{% endif %}"><a href="/">Main</a></li>
            <li role="presentation" class="{% if active_tab == 'popular' %}active{% endif %}"><a href="/popular/">Popular</a></li>
            <li role="presentation" class="{% if active_tab == 'add' %}active{% endif %}"><a href="/add/">Add image</a></li>
            {% if not user.is_anonymous %}
                <li role="presentation" class="{% if active_tab == 'private' %}active{% endif %}"><a href="/private">Private</a></li>
            {% endif %}
            {% if image_info %}
                <li role="presentation" class="active"><a href="/{{ image_info }}/">{{ image_info }}</a></li>
            {% endif %}
        </ul>
    </div>

picture_sharing/templates/image.html
{% include "header.html" %}
    <div class="container">
        <div class="panel panel-info">
            <div class="panel-heading"><div style="float: left">{{ page_title }}</div>
                <div align="right" >
                <a class="btn btn-info btn-sm" href='/delete/{{ picture.key }}' role="button"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete</a>
                <!--<a class="btn btn-info btn-sm" id='btn-like' role="button"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Like</a>-->
                <button type="button" class="btn btn-info btn-sm" id="btn-like" onclick="Likeaction()"><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>Like</button>
                </div>
                <script>
                    function Likeaction(){
                    $.ajax({
                        type: "POST",
                        url: "like",
                        data: {'key': '{{ picture.key }}', 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                        dataType: "json",
                        success: function(response) {
                                $('#likes_count').text(response.likes_count);
                        },
                        error: function(rs, e) {
                                alert(rs.responseText);
                        }
                        }); 
                    }
                </script>
            </div>
            <div style="padding:15px">
                <p></p>
                <dl class="dl-horizontal">
                <dt>User</dt><dd>{{ picture.user }}</dd>
                <dt>Key</dt><dd>{{ picture.key }}</dd>
                <dt>Description</dt><dd>{{ picture.description }}</dd>
                <dt>Created</dt><dd>{{ picture.date_created }}</dd>
                <dt>Last viewed</dt><dd>{{ picture.date_last_view }}</dd>
                <dt>Views count</dt><dd>{{ picture.views_count }}</dd>
                <dt>Likes</dt><dd id="likes_count">{{ likes }}</dd>
                <dt>Dimensions (px)</dt><dd>{{ picture.image.width }} x {{ picture.image.height }}</dd>
                <dt>Image filename</dt><dd>{{ picture.image }}</dd>
                <dt>Image size (bytes)</dt><dd>{{ picture.image.size }}</dd>
                </dl>
                <img class='img-responsive' src="{{ picture.image.url }}" alt="{{picture.description}}">
            </div>
        </div>        
    </div>


{% include "footer.html" %}

picture_sharing/templates/index.html
{% include "header.html" %}
    
    <div class="container">
        <div class="panel panel-info">
        <div class="panel-heading">{{ page_title }}</div>
        <div class="container-fluid" style="padding-top:15px">
            <article class="row">
            {% for picture in pictures %}
                <div class="col-md-4">
                <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="/{{ picture.key }}">{{ picture.key }}</a>
                </div>
                    <!--<p>{{ picture.image }}</p>-->
                    <p style="margin-left:5px"><b>Decription:</b> {{ picture.description }}</p>
                    <p style="margin-left:5px"><b>Created:</b> {{ picture.date_created }}</p>
                    <p style="margin-left:5px"><b>Views:</b> {{ picture.views_count }}</p>
                    <p style="margin-left:5px"><b>User:</b> {{ picture.user}}</p>
                    <a href="/{{ picture.key }}" class="thumbnail">
                        <img src="{{ picture.image.url }}" alt="{{picture.description}}" class="img-responsive">
                    </a>
                </div>
                </div>
                {% if forloop.counter == 3 %}
                    <article class="row"></article>
                {% endif %}
                {% if forloop.counter == 6 %}
                    <article class="row"></article>
                {% endif %}
                {% if forloop.counter == 9 %}
                    <article class="row"></article>
                {% endif %}
                
            {% endfor %}
            </article>
        </div>
        </div>
    </div>
    
{% include "footer.html" %}